package com.devpath.integration.application;

public enum IntegrationAuditEvent {
    GITHUB_CONNECTED,
    GITHUB_DISCONNECTED,
    GITHUB_TOKEN_REFRESH_FAILED,
    GITHUB_PERMISSION_CHANGED,
    GITHUB_RATE_LIMITED,
    NOTION_CONNECTED,
    NOTION_DISCONNECTED,
    NOTION_PERMISSION_CHANGED,
    NOTION_RATE_LIMITED,
    NOTION_METADATA_DISCOVERED
}
