import { screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { Route, Routes } from "react-router-dom";
import { renderWithProviders } from "../test/renderWithProviders";
import { AnalysisComparisonPage } from "./AnalysisComparisonPage";

afterEach(()=>vi.unstubAllGlobals());
const metadata={requestId:"request-1",apiVersion:"v1",timestamp:"2026-08-25T00:00:00Z"};
const summary=(analysisId:string,evaluationId:string,score:number)=>({analysisId,repositoryId:"repository-1",repositoryFullName:"owner/devpath",snapshotId:`snapshot-${analysisId}`,evaluationId,skillMatrixId:`matrix-${analysisId}`,analysisScope:"REPOSITORY_BASELINE",overallScore:score,confidence:90,ruleSetVersion:"baseline-v2",policyVersion:"skill-matrix-v2",currentForRepository:analysisId==="analysis-b",completedAt:"2026-08-25T00:00:00Z"});
const evaluation=(evaluationId:string,score:number,categoryScore:number)=>({evaluationId,snapshotId:`snapshot-${evaluationId}`,ruleSetVersionId:"version-1",ruleSetVersion:"baseline-v2",formulaLibraryVersion:"formula-v1",extractorVersion:"extractor-v2",overallScore:score,confidence:90,evidenceSummary:{evidenceCount:2,rulesWithEvidence:1,missingEvidenceCount:0},categoryScores:[{category:"TESTING",score:categoryScore,weight:.2,confidence:90,ruleResults:[{ruleId:"TEST_FILES",ruleVersion:"1",status:"PASSED",rawValue:1,score:categoryScore,weight:1,formulaId:"PRESENCE",trace:"TEST_FILES=1",evidenceReferences:["tests"]}],missingEvidence:[]}],warnings:[],completedAt:"2026-08-25T00:00:00Z"});

it("compares two stored official results without calculating a delta",async()=>{vi.stubGlobal("fetch",vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.includes("/analyses/compare?"))return Promise.resolve(Response.json({data:{analyses:[summary("analysis-a","evaluation-a",70),summary("analysis-b","evaluation-b",82)]},metadata}));if(url.endsWith("/rule-evaluations/evaluation-a"))return Promise.resolve(Response.json({data:evaluation("evaluation-a",70,60),metadata}));if(url.endsWith("/rule-evaluations/evaluation-b"))return Promise.resolve(Response.json({data:evaluation("evaluation-b",82,85),metadata}));return Promise.reject(new Error(url));}));renderWithProviders(<Routes><Route path="/analyses/compare" element={<AnalysisComparisonPage/>}/></Routes>,["/analyses/compare?analysisId=analysis-a&analysisId=analysis-b"]);expect(await screen.findByRole("heading",{name:"분석 결과 비교"})).toBeInTheDocument();expect(screen.getAllByText("owner/devpath")).toHaveLength(2);expect(screen.getByRole("row",{name:/테스트 60/})).toHaveTextContent("85");expect(screen.getByText(/차이 점수나 향상률을 새로 계산하지 않습니다/)).toBeInTheDocument();});
