import { Link, useSearchParams } from "react-router-dom";
import type { RuleCategoryScore } from "../features/analysis/api/analysisApi";
import { useAnalysisComparison } from "../features/analysis/model/useAnalysis";
import { ApiError } from "../shared/api/apiClient";

const categories:RuleCategoryScore["category"][]=["LANGUAGE","FRAMEWORK","TESTING","DOCUMENTATION","ACTIVITY"];

export function AnalysisComparisonPage(){const [params]=useSearchParams();const ids=params.getAll("analysisId");const valid=ids.length===2&&ids[0]!==ids[1];const query=useAnalysisComparison(ids);if(!valid)return <Shell><section className="state-panel" role="alert"><h1>비교할 분석 두 개를 선택해 주세요</h1><p>서로 다른 완료 분석 두 개가 필요합니다.</p><Link className="button-link" to="/analyses">분석 이력으로 이동</Link></section></Shell>;if(query.isPending)return <Shell><p role="status">두 분석의 공식 결과를 불러오는 중입니다.</p></Shell>;if(query.isError)return <Shell><ErrorState error={query.error} retry={()=>query.refetch()}/></Shell>;const [left,right]=query.data.analyses;return <Shell>
  <header className="workspace-header"><div><p className="eyebrow">Authoritative Result Comparison</p><h1>분석 결과 비교</h1><p>저장된 두 Rule Engine 결과를 나란히 표시합니다. 이 화면은 차이 점수나 향상률을 새로 계산하지 않습니다.</p></div><Link className="button-link" to="/analyses">다른 분석 선택</Link></header>
  <aside className="analysis-notice"><div><h2>기술 역량까지 비교하기</h2><p>두 분석에서 생성된 불변 Skill Matrix의 점수, 등급, 근거를 이어서 확인할 수 있습니다.</p></div><Link className="button-link" to={`/skills/compare?skillMatrixId=${left.summary.skillMatrixId}&skillMatrixId=${right.summary.skillMatrixId}`}>기술 역량 비교</Link></aside>
  <section className="comparison-hero" aria-label="비교 대상"><ComparisonSummary label="분석 A" item={left}/><div aria-hidden="true">VS</div><ComparisonSummary label="분석 B" item={right}/></section>
  <section aria-labelledby="category-comparison-title"><div className="section-heading"><div><h2 id="category-comparison-title">범주별 공식 결과</h2><p>각 값은 해당 분석에 저장된 규칙 버전의 결과입니다. 결과가 없는 범주는 계산하지 않고 ‘없음’으로 표시합니다.</p></div></div><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th scope="col">범주</th><th scope="col">분석 A</th><th scope="col">분석 B</th></tr></thead><tbody>{categories.map(category=><ComparisonRow key={category} category={category} left={categoryScore(left.evaluation.categoryScores,category)} right={categoryScore(right.evaluation.categoryScores,category)}/>)}</tbody></table></div></section>
  <section className="comparison-rule-grid" aria-label="규칙 버전과 근거 요약"><EvaluationFacts label="분석 A" item={left}/><EvaluationFacts label="분석 B" item={right}/></section>
</Shell>}
function ComparisonSummary({label,item}:{label:string;item:{summary:import("../features/analysis/api/analysisApi").AnalysisHistoryItem;evaluation:import("../features/analysis/api/analysisApi").RuleEvaluation}}){return <article><span>{label}</span><h2>{item.summary.repositoryFullName}</h2><div><strong>{format(item.evaluation.overallScore)}</strong><span>/ 100</span></div><time dateTime={item.summary.completedAt}>{date(item.summary.completedAt)}</time><Link to={`/analyses/${item.summary.analysisId}`}>전체 근거 보기</Link></article>}
function ComparisonRow({category,left,right}:{category:RuleCategoryScore["category"];left:RuleCategoryScore|undefined;right:RuleCategoryScore|undefined}){return <tr><th scope="row">{categoryLabel(category)}</th><ResultCell value={left}/><ResultCell value={right}/></tr>}
function ResultCell({value}:{value:RuleCategoryScore|undefined}){return <td>{value?<><strong>{format(value.score)}</strong><small>신뢰도 {format(value.confidence)}% · 규칙 {value.ruleResults.length}개</small></>:<span>없음</span>}</td>}
function EvaluationFacts({label,item}:{label:string;item:{summary:import("../features/analysis/api/analysisApi").AnalysisHistoryItem;evaluation:import("../features/analysis/api/analysisApi").RuleEvaluation}}){return <article><h2>{label} 재현 정보</h2><dl><div><dt>규칙 세트</dt><dd>{item.evaluation.ruleSetVersion}</dd></div><div><dt>공식 계산식</dt><dd>{item.evaluation.formulaLibraryVersion}</dd></div><div><dt>추출기</dt><dd>{item.evaluation.extractorVersion}</dd></div><div><dt>연결 근거</dt><dd>{item.evaluation.evidenceSummary.evidenceCount}개</dd></div><div><dt>누락 근거</dt><dd>{item.evaluation.evidenceSummary.missingEvidenceCount}개</dd></div></dl></article>}
function ErrorState({error,retry}:{error:Error;retry:()=>void}){if(error instanceof ApiError&&(error.status===404||error.status===401))return <section className="state-panel" role="alert"><h1>{error.status===401?"로그인이 필요합니다":"비교할 분석을 찾을 수 없습니다"}</h1><Link className="button-link" to={error.status===401?"/":"/analyses"}>{error.status===401?"로그인 화면으로 이동":"분석 이력으로 이동"}</Link></section>;return <section className="state-panel" role="alert"><h1>분석 비교 결과를 불러오지 못했습니다</h1><button type="button" onClick={retry}>다시 시도</button></section>}
function Shell({children}:{children:React.ReactNode}){return <main className="shell workspace"><nav><Link to="/dashboard">대시보드</Link></nav>{children}</main>}
function categoryScore(values:RuleCategoryScore[],category:RuleCategoryScore["category"]){return values.find(item=>item.category===category)}
function categoryLabel(value:RuleCategoryScore["category"]){return {LANGUAGE:"언어",FRAMEWORK:"프레임워크",TESTING:"테스트",DOCUMENTATION:"문서화",ACTIVITY:"활동"}[value]}
function format(value:number){return new Intl.NumberFormat("ko-KR",{maximumFractionDigits:2}).format(value)}
function date(value:string){return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
