import { Link } from "react-router-dom";
import type { Recommendation, RoadmapStep } from "../features/recommendations/api/recommendationApi";
import { useRecommendationJourney } from "../features/recommendations/model/useRecommendationJourney";
import { ApiError } from "../shared/api/apiClient";

export function LearningRoadmapPage(){const query=useRecommendationJourney();if(query.isPending)return <Shell><p role="status">추천과 학습 로드맵을 불러오는 중입니다…</p></Shell>;if(query.isError)return <Shell><JourneyError error={query.error} retry={()=>query.refetch()}/></Shell>;const {recommendations,roadmap}=query.data;return <Shell>
  <header className="workspace-header"><div><p className="eyebrow">Deterministic Learning Plan</p><h1>추천 및 학습 로드맵</h1><p>공식 skill gap과 승인된 정책으로 생성된 구조화 결과입니다. AI 설명은 포함하지 않습니다.</p></div><div className="analysis-version"><span>추천 {recommendations.policyVersion}</span><span>로드맵 {roadmap.policyVersion}</span></div></header>
  <section className="roadmap-summary" aria-label="로드맵 요약"><div><strong>{recommendations.recommendations.length}</strong><span>현재 추천</span></div><div><strong>{roadmap.steps.length}</strong><span>학습 단계</span></div><div><strong>{formatNumber(roadmap.progressPercent)}%</strong><span>진행률</span></div></section>
  {recommendations.recommendations.length===0?<section className="state-panel"><h2>현재 개선 추천이 없습니다</h2><p>현재 필수 범주가 모두 충분 이상입니다. 새 분석이 완료되면 정책 기준으로 다시 생성됩니다.</p></section>:<>
  <section aria-labelledby="recommendations-title"><div className="section-heading"><div><h2 id="recommendations-title">우선 추천</h2><p>Missing, Weak, Partial 순서와 직무 가중치·선행 순서를 반영합니다.</p></div></div><div className="recommendation-grid">{recommendations.recommendations.map(item=><RecommendationCard key={item.recommendationId} item={item}/>)}</div></section>
  <section aria-labelledby="roadmap-title"><div className="section-heading"><div><h2 id="roadmap-title">실행 순서</h2><p>앞 단계가 다음 단계의 명시적 prerequisite로 연결됩니다.</p></div></div><ol className="roadmap-step-list">{roadmap.steps.map(step=><StepCard key={step.roadmapStepId} step={step}/>)}</ol></section></>}
</Shell>;}
function RecommendationCard({item}:{item:Recommendation}){return <article className={`recommendation-card recommendation-card--${item.priority.toLowerCase()}`}><div><span>{categoryLabel(item.category)}</span><strong>{priorityLabel(item.priority)}</strong></div><h3>{item.title}</h3><p>{item.completionCriteria}</p><small>{typeLabel(item.type)} · 예상 {item.effortHours}시간 · 근거 {item.evidenceIds.length}개</small></article>;}
function StepCard({step}:{step:RoadmapStep}){return <li><span>{step.position+1}</span><article><div><h3>{step.title}</h3><strong>{difficultyLabel(step.difficulty)}</strong></div><p>{step.completionCriteria}</p><details><summary>필요한 측정 근거</summary><ul>{step.expectedEvidence.map(item=><li key={item}>{item}</li>)}</ul></details><small>예상 {step.effortHours}시간 · 선행 단계 {step.prerequisiteStepIds.length}개</small></article></li>;}
function JourneyError({error,retry}:{error:Error;retry:()=>void}){if(error instanceof ApiError&&error.status===404)return <div className="state-panel"><h1>아직 추천 로드맵이 없습니다</h1><p>Backend 또는 Frontend 목표로 새 분석을 완료하면 자동 생성됩니다.</p><Link className="button-link" to="/repositories">분석 준비</Link></div>;if(error instanceof ApiError&&error.status===401)return <div className="state-panel" role="alert"><h1>로그인이 필요합니다</h1><Link className="button-link" to="/">로그인 화면으로 이동</Link></div>;return <div className="state-panel" role="alert"><h1>추천 로드맵을 불러오지 못했습니다</h1><button type="button" onClick={retry}>다시 시도</button></div>;}
function Shell({children}:{children:React.ReactNode}){return <main className="shell workspace"><nav><Link to="/dashboard">← 대시보드</Link></nav>{children}</main>;}
function formatNumber(value:number){return new Intl.NumberFormat("ko-KR",{maximumFractionDigits:2}).format(value);}
function categoryLabel(value:string){return {LANGUAGE:"언어",FRAMEWORK:"프레임워크",DATABASE:"데이터베이스",ARCHITECTURE:"아키텍처",TESTING:"테스트",DEVOPS:"DevOps",DOCUMENTATION:"문서화",ACTIVITY:"활동"}[value]??value;}
function priorityLabel(value:Recommendation["priority"]){return {CRITICAL:"긴급",HIGH:"높음",MEDIUM:"보통",LOW:"낮음"}[value];}
function typeLabel(value:Recommendation["type"]){return {STUDY:"학습",PROJECT:"프로젝트",ARCHITECTURE:"아키텍처",PORTFOLIO:"포트폴리오"}[value];}
function difficultyLabel(value:RoadmapStep["difficulty"]){return {BEGINNER:"입문",INTERMEDIATE:"중급",ADVANCED:"고급"}[value];}
