import { Link, useParams } from "react-router-dom";
import { useRecommendationDetail } from "../features/recommendations/model/useRecommendations";
import { ApiError } from "../shared/api/apiClient";

export function RecommendationDetailPage(){const {recommendationId=""}=useParams();const query=useRecommendationDetail(recommendationId);if(query.isPending)return <Shell><p role="status">추천 상세와 근거를 불러오는 중입니다.</p></Shell>;if(query.isError)return <Shell><ErrorState error={query.error} retry={()=>query.refetch()}/></Shell>;const {recommendation,evidence}=query.data;return <Shell>
  <header className="workspace-header"><div><p className="eyebrow">{recommendation.category} · {recommendation.priority}</p><h1>{recommendation.title}</h1><p>추천 정책이 기록한 완료 기준과 연결된 관찰 근거를 함께 확인합니다.</p></div><div className="analysis-version"><span>{recommendation.type}</span><span>{recommendation.status}</span></div></header>
  <section className="recommendation-detail-grid" aria-label="추천 상세"><article><h2>완료 기준</h2><p>{recommendation.completionCriteria}</p></article><article><h2>실행 정보</h2><dl><div><dt>예상 노력</dt><dd>{recommendation.effortHours}시간</dd></div><div><dt>결정론적 근거 코드</dt><dd><code>{recommendation.rationaleCode}</code></dd></div><div><dt>세트 내 순서</dt><dd>{recommendation.position+1}번째</dd></div></dl></article></section>
  <section aria-labelledby="expected-evidence-title"><div className="section-heading"><div><h2 id="expected-evidence-title">기대하는 측정 근거</h2><p>추천을 완료했다고 판단할 때 필요한 산출물입니다.</p></div></div><ul className="expected-evidence-list">{recommendation.expectedEvidence.map(item=><li key={item}>{item}</li>)}</ul></section>
  <section aria-labelledby="observed-evidence-title"><div className="section-heading"><div><h2 id="observed-evidence-title">현재 연결된 관찰 근거</h2><p>공식 분석에서 보존된 사용자 소유 근거만 표시합니다.</p></div><span className="status-badge">{evidence.length}개</span></div>{evidence.length===0?<div className="state-panel"><h3>연결된 관찰 근거가 없습니다</h3><p>이 추천은 현재 Skill Gap을 채울 새로운 근거를 만들도록 안내합니다.</p></div>:<div className="recommendation-evidence-list">{evidence.map(item=><article key={item.evidenceId}><header><strong>{item.evidenceType}</strong><span>신뢰도 {formatNumber(item.confidence)}%</span></header><p>{item.observedFactSummary}</p><code>{item.sourceReference}</code><time dateTime={item.createdAt}>{formatDate(item.createdAt)}</time></article>)}</div>}</section>
</Shell>}
function ErrorState({error,retry}:{error:Error;retry:()=>void}){if(error instanceof ApiError&&error.status===404)return <section className="state-panel" role="alert"><h1>추천을 찾을 수 없습니다</h1><Link className="button-link" to="/recommendations">추천 이력으로 이동</Link></section>;if(error instanceof ApiError&&error.status===401)return <section className="state-panel" role="alert"><h1>로그인이 필요합니다</h1><Link className="button-link" to="/">로그인 화면으로 이동</Link></section>;return <section className="state-panel" role="alert"><h1>추천 상세를 불러오지 못했습니다</h1><button type="button" onClick={retry}>다시 시도</button></section>}
function Shell({children}:{children:React.ReactNode}){return <main className="shell workspace"><nav><Link to="/recommendations">추천 작업공간</Link></nav>{children}</main>}
function formatNumber(value:number){return new Intl.NumberFormat("ko-KR",{maximumFractionDigits:2}).format(value)}
function formatDate(value:string){return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
