import { Link } from "react-router-dom";
import { useRecommendationHistory } from "../features/recommendations/model/useRecommendations";
import { ApiError } from "../shared/api/apiClient";

export function RecommendationsPage(){const query=useRecommendationHistory();if(query.isPending)return <Shell><p role="status">추천 이력을 불러오는 중입니다.</p></Shell>;if(query.isError)return <Shell><ErrorState error={query.error} retry={()=>query.refetch()}/></Shell>;const sets=query.data;const recommendationCount=sets.reduce((total,set)=>total+set.recommendations.length,0);return <Shell>
  <header className="workspace-header"><div><p className="eyebrow">Deterministic Recommendations</p><h1>추천 작업공간</h1><p>공식 Skill Gap과 버전 관리된 정책으로 생성된 추천을 시간순으로 확인합니다. AI가 우선순위나 완료 기준을 계산하지 않습니다.</p></div><div className="workspace-actions"><Link to="/career-readiness">커리어 준비도</Link><Link className="button-link" to="/roadmap">학습 로드맵</Link></div></header>
  <section className="recommendation-history-summary" aria-label="추천 이력 요약"><div><strong>{sets.length}</strong><span>추천 세트</span></div><div><strong>{recommendationCount}</strong><span>전체 추천</span></div><div><strong>{sets.filter(set=>set.status==="PUBLISHED").length}</strong><span>현재 세트</span></div></section>
  {sets.length===0?<section className="state-panel"><h2>아직 생성된 추천이 없습니다</h2><p>결정론적 분석과 커리어 준비도 평가가 완료되면 측정 가능한 추천이 생성됩니다.</p><Link className="button-link" to="/repositories">분석 준비</Link></section>:<section aria-labelledby="recommendation-history-title"><div className="section-heading"><div><h2 id="recommendation-history-title">추천 세트 이력</h2><p>과거 추천은 변경하지 않고 생성 당시 정책 버전과 상태를 보존합니다.</p></div></div><div className="recommendation-set-list">{sets.map(set=><article className="recommendation-set" key={set.recommendationSetId}><header><div><span className={`status-badge${set.status==="PUBLISHED"?" status-badge--active":""}`}>{set.status==="PUBLISHED"?"현재 적용":"과거 세트"}</span><h3>{set.policyVersion}</h3><Link to={`/career-readiness/${set.careerReadinessId}`}>준비도 근거 보기</Link></div><time dateTime={set.generatedAt}>{formatDate(set.generatedAt)}</time></header><ol>{set.recommendations.map(item=><li key={item.recommendationId}><div><span>{categoryLabel(item.category)}</span><strong>{priorityLabel(item.priority)}</strong></div><h4>{item.title}</h4><p>{item.completionCriteria}</p><footer><small>{typeLabel(item.type)} · 예상 {item.effortHours}시간 · 근거 {item.evidenceIds.length}개</small><Link to={`/recommendations/${item.recommendationId}`}>상세 근거 보기</Link></footer></li>)}</ol></article>)}</div></section>}
</Shell>}
function ErrorState({error,retry}:{error:Error;retry:()=>void}){const anonymous=error instanceof ApiError&&error.status===401;return <section className="state-panel" role="alert"><h1>{anonymous?"로그인이 필요합니다":"추천 이력을 불러오지 못했습니다"}</h1>{anonymous?<Link className="button-link" to="/">로그인 화면으로 이동</Link>:<button type="button" onClick={retry}>다시 시도</button>}</section>}
function Shell({children}:{children:React.ReactNode}){return <main className="shell workspace"><nav><Link to="/dashboard">대시보드</Link></nav>{children}</main>}
function formatDate(value:string){return new Intl.DateTimeFormat("ko-KR",{dateStyle:"long",timeStyle:"short"}).format(new Date(value))}
function categoryLabel(value:string){return {LANGUAGE:"언어",FRAMEWORK:"프레임워크",DATABASE:"데이터베이스",ARCHITECTURE:"아키텍처",TESTING:"테스트",DEVOPS:"DevOps",DOCUMENTATION:"문서화",ACTIVITY:"활동"}[value]??value}
function priorityLabel(value:string){return {CRITICAL:"긴급",HIGH:"높음",MEDIUM:"보통",LOW:"낮음"}[value]??value}
function typeLabel(value:string){return {STUDY:"학습",PROJECT:"프로젝트",ARCHITECTURE:"아키텍처",PORTFOLIO:"포트폴리오"}[value]??value}
